export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <header style={{
          backgroundColor: "yellowgreen",
          padding: "1erm",
           justifyItems: "center"
        }}>
       <p>Header</p>
        </header>
        
        <main
        style={{
          justifyItems: "center"
        }}
        >
          {children}
        </main>

        <footer
        style={{
          backgroundColor : "ghostwhite",
          padding: "1erm",
          justifyItems: "center"
        }}
        >
       <p>   Footer</p>
        </footer>
        
        </body>
    </html>
  )
}
